apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
   app: {{ template "fullname" . }}
   chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
   release: "{{ .Release.Name }}"
   heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
#      securityContext:
#        runAsUser: 1001
#        fsGroup: 1001
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        ports:
        - name: exporthttp
          containerPort: {{ .Values.service.externalPortHttp }}
        - name: inporthttp
          containerPort: {{ .Values.service.internalPortHttp }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPortHttp }}
          initialDelaySeconds: 180
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPortHttp }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
