# Default values for mean-k8s.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: gcr.io/cryptocurrencyservices-197520/cryptocurrency-services-gateway
  tag: 0.1.0
  pullPolicy: Always
service:
  name: cryptocurrency-services-gateway
  type: NodePort
  externalPort: 8080
  internalPort: 8080
#resources:
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

