apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels:
   app: {{ template "fullname" . }}
   chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
   release: "{{ .Release.Name }}"
   heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
#      securityContext:
#        runAsUser: 1001
#        fsGroup: 1001
      initContainers:
          - name: init-sysctl
            image: busybox:1.27.2
            command:
            - sysctl
            - -w
            - vm.max_map_count=262144
            securityContext:
              privileged: true
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
#        env:
#        - name: MAX_MAP_COUNT
#          value: "262144"
#        command: ["sysctl -w vm.max_map_count=262144 && /elasticsearch/bin/elasticsearch"]
#        command: ["/elasticsearch/bin/elasticsearch"]
#        command: ["ls -al /usr/share/elasticsearch"]
#        command: ["/bin/sh","-c"]
#        args: ["ls -al /usr/share/elasticsearch; sysctl -w vm.max_map_count=262144 && /usr/share/elasticsearch/bin/elasticsearch"]
        ports:
        - name: exporthttp
          containerPort: {{ .Values.service.externalPortHttp }}
        - name: inporthttp
          containerPort: {{ .Values.service.internalPortHttp }}
        livenessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPortHttp }}
          initialDelaySeconds: 180
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: {{ .Values.service.internalPortHttp }}
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.resources | indent 12 }}
