apiVersion: v1
kind: Service
metadata:
#  name: {{ .Release.Name }}-service
  name: {{ .Chart.Name }}-service
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: {{ .Values.service.type }}
#  loadBalancerIP: 35.227.201.36
  ports:
  - port: {{ .Values.service.externalPortHttp }}
    targetPort: {{ .Values.service.inPortHttp }}
    protocol: TCP
    name: {{ .Values.service.nameHttp }}
  - port: {{ .Values.service.externalPortTransport }}
    targetPort: {{ .Values.service.internalPortTransport }}
    protocol: TCP
    name: {{ .Values.service.nameTransport }}
  selector:
    app: {{ template "fullname" . }}
#    tier: web
