version: '2'
services:
    masternodesonlinesupplement-app:
        image: masternodesonlinesupplement
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@jhipster-registry:8761/config
            - SPRING_DATA_MONGODB_URI=mongodb://masternodesonlinesupplement-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=MasternodesOnlineSupplement
            - JHIPSTER_SLEEP=30 # gives time for the JHipster Registry to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=masternodesonlinesupplement-elasticsearch:9300
    masternodesonlinesupplement-mongodb:
        extends:
            file: mongodb.yml
            service: masternodesonlinesupplement-mongodb
    masternodesonlinesupplement-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: masternodesonlinesupplement-elasticsearch
    jhipster-registry:
        extends:
            file: jhipster-registry.yml
            service: jhipster-registry
        environment:
            - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=file:./central-config/docker-config/
